### ISSUE TITLE
missing severity in create_event.json object?

### ISSUE THREAD

**Issue by cl0udgeek** [PagerDuty/go-pagerduty#100]
I think we're missing `severity` in the `create_json` object defined by . `type Event struct`...

https://github.com/PagerDuty/go-pagerduty/blob/master/event.go#L13

**Comment by tmccleve** [comment]
Severity is a v2 API parameter. https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2

v1 events: https://v2.developer.pagerduty.com/docs/trigger-events

Per: https://github.com/PagerDuty/go-pagerduty/blob/master/event.go#L10 this library is referencing the v1 api.

**Comment by tmccleve** [comment]
@k1ng87 I did spike out something a while back to deal with this, FYI. https://github.com/WTW-IM/prtg-pagerduty/blob/master/event/event.go

**Comment by stmcallister** [comment]
Closing old issue. This appears to be addressed. Please reopen or post another issue if there needs to be more discussion.
