### ISSUE TITLE
Add A CODEOWNERS file for easier review requests.

### ISSUE THREAD

**Issue by whithajess** [PagerDuty/go-pagerduty#124]
This Project doesn't seem to be getting a lot of love in the PR space.

Would like to suggest adding a CODEOWNERS file see https://help.github.com/articles/about-codeowners/ for how it works.

hopefully get a bit more love for people adding to this project.

**Comment by whithajess** [comment]
Will help with this: https://github.com/PagerDuty/go-pagerduty/pull/108

**Comment by stmcallister** [comment]
Thanks for the suggestion! We're putting more effort into addressing PRs in a more timely manner. Appreciate the feedback.
