### ISSUE TITLE
Missing Services Extensions available over API

### ISSUE THREAD

**Issue by abtris** [PagerDuty/go-pagerduty#129]
- I can check if we have correct webhooks set at every service and didn't find that in SDK

**Comment by evelinfong** [comment]
Not sure if this is what you are looking for, https://github.com/PagerDuty/go-pagerduty/blob/master/service.go#L94.
In Go, you can call ListServices and it will be able to print out all the services you have and the webhook that you have set up. 
Or if you are interested in listing all the extensions to check for correct webhook, you can do a simple curl with your Pagerduty token:
https://api-reference.pagerduty.com/#!/Extensions/get_extensions

**Comment by abtris** [comment]
Yes, I can do with curl but why I will use SDK if I can write all by myself.

**Comment by chenrui333** [comment]
This would be something useful from PD forum as workaround to address Slack extension setup:
https://community.pagerduty.com/t/how-to-pass-config-data-when-creating-an-extension/1857/2

**Comment by stmcallister** [comment]
PR #193 appears to have addressed this. Please reopen if that's not the case.
