### ISSUE TITLE
incident_key for create_event

### ISSUE THREAD

**Issue by tj** [PagerDuty/go-pagerduty#13]
Hey! Unless I'm missing something it looks like pagerduty.Event is missing an IncidentKey field for https://v2.developer.pagerduty.com/v2/docs/trigger-events. I'm also not seeing incident_keys UUIDs generated for the response.

**Comment by ranjib** [comment]
Thank @tj  for reporting this. I have just merged https://github.com/PagerDuty/go-pagerduty/pull/21 and https://github.com/PagerDuty/go-pagerduty/pull/20 , let me know if this is still an issue
