### ISSUE TITLE
Webhook decoder

### ISSUE THREAD

**Issue by abh** [PagerDuty/go-pagerduty#14]
It'd be nice if there was a struct defined for the [webhook payload](https://v2.developer.pagerduty.com/docs/webhooks-overview).

**Comment by ranjib** [comment]
@abh I have taken a stab at it, but yet to test it out, let me know if this works, or anything else you need, and thanks for the suggestion, appreciate it :-)
https://github.com/PagerDuty/go-pagerduty/pull/22
