### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by jontonsoup** [PagerDuty/go-pagerduty#146]
The last release was May 28, 2018. This breaks dep with the defaults.

**Comment by NautiluX** [comment]
With the latest release it's not possible to use [v2 event api](https://github.com/PagerDuty/go-pagerduty/blob/master/event_v2.go), am I right? Would be great to have this, so I'd as well appreciate a new release :+1:

**Comment by stmcallister** [comment]
@NautiluX I'm not seeing this. Are you using the library directly or the CLI?

**Comment by NautiluX** [comment]
I think 1.1.1 contains the changes for the v2 event api. Thanks for creating the release! However, I think issue #186 has not been addressed, which means the lib cannot parse v2 event api responses.

**Comment by stmcallister** [comment]
@NautiluX Sounds good. I'll take a look at #186 soon!
