### ISSUE TITLE
Mock Client?

### ISSUE THREAD

**Issue by dmathieu** [PagerDuty/go-pagerduty#148]
In order to be able to write unit tests for a package using this one as a dependency, it would be nice to be able to mock it.

Making the `Client` into an interface, with a `struct` implementing everything it does would allow creating additional structs which implement the interface too, to mock the behavior.

**Comment by simar7** [comment]
I agree with what @dmathieu has said. Currently anything that's not a method on ```Client``` needs to be monkey-patched for unit testing, rather than being able to dependency inject it. This is particularly needed for ```CreateEvent()``` 

Would this be something on the roadmap for this library?

**Comment by stmcallister** [comment]
Recent PRs ( #173 and #190) appear to have addressed this. Going to close. Please reopen if this has not been addressed.

**Comment by goatherder** [comment]
I don't think this has been fully addressed - there are still some client functions that don't use the client struct - so we cannot override anything.  eg: for v2 events - ManageEvent.

I have opened a PR which addresses this.
