### ISSUE TITLE
Create service extension (like slack extension) over API

### ISSUE THREAD

**Issue by chenrui333** [PagerDuty/go-pagerduty#149]
relates to #129 

I wonder if I can programmatically create slack extension for pagerduty service.

**Comment by chenrui333** [comment]
This would be something useful from PD forum as workaround to address Slack extension setup:
https://community.pagerduty.com/t/how-to-pass-config-data-when-creating-an-extension/1857/2

**Comment by stmcallister** [comment]
PR #193 appears to have addressed this. Please reopen if that's not the case.
