### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by PaulCapestany** [PagerDuty/go-pagerduty#15]
Pagerduty is misspelled. 

![image](https://cloud.githubusercontent.com/assets/458245/17337226/91bf263e-5896-11e6-8163-1ef62807f384.png)

**Comment by ranjib** [comment]
oops. thanks @PaulCapestany . FIxed

**Comment by PaulCapestany** [comment]
Almost ;)

"go client library for Pager**_t_**Duty v2 API"

**Comment by ranjib** [comment]
damn! done :-)
