### ISSUE TITLE
Documentation does not match code

### ISSUE THREAD

**Issue by Luzifer** [PagerDuty/go-pagerduty#16]
The README and repository description states this is a library using your v2 API. Taking a look into the `client.go` it uses the v1 endpoint so this is in fact not a v2 library…

Also for example `CreateOverride` does send invalid data according to the specification of the v2 API documentation. Even when patching the data the response code handling is broken…

Please label this as an v1 library or port it to v2.

**Comment by dthagard** [comment]
I've overhauled the SDK to work correctly with V2 in this PR:  https://github.com/PagerDuty/go-pagerduty/pull/23

**Comment by ranjib** [comment]
@Luzifer as @dthagard  the library now has v2 api. I had made some fixes soon after you raise the issue, as well. Let us know if you think its still not matching the v2 API. This is under active development, and not quiet ready yet (does not cover the entire API).
