### ISSUE TITLE
Update logrus imports to github.com/sirupsen/logrus

### ISSUE THREAD

**Issue by ebracho** [PagerDuty/go-pagerduty#160]
The logrus owner recently changed the case of their handle (Sirupsen -> sirupsen). This causes issues on case-insensitive filesystems (like in macos), since vendoring both versions of the package results in filepath collisions. The logrus maintainer has stated that they will keep the new name (see https://github.com/sirupsen/logrus/issues/570), so it is up to other packages to update their imports.

**Comment by fxfactorial** [comment]
I am getting this issue as well: 

```
 go build -o $GOPATH/bin/pd command/*
go: finding github.com/google/go-querystring/query latest
go: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```

@stmcallister Can you please suggest a fix? I just want to just use `pd service list`

I looked at releases as well hoping that project would provide precompiled binaries (I need OS X) but it wasn't there either, i think that would be a good idea.

**Comment by stmcallister** [comment]
Thanks for pointing this out! I'll take a look at this. But, it may not be until after the PagerDuty Summit conference next week.

**Comment by stmcallister** [comment]
This was addressed with [PR 168](https://github.com/PagerDuty/go-pagerduty/pull/168).
