### ISSUE TITLE
failed to create an incident

### ISSUE THREAD

**Issue by chunyanlv** [PagerDuty/go-pagerduty#165]
Here is my code:
```
        opts := officialPD.CreateIncidentOptions{
                Type: "incident",
                Title: title,
                Service: &service,
                Body: &body,
                EscalationPolicy: &escalationPolicy,
        }
 _, err := client.CreateIncident(INCIDENT_FROM, &opts)
```
I have the title correctly set.
But I got the error like:
```
panic: Failed call API endpoint. HTTP response code: 400. Error: &{2001 Invalid Input Provided [Title cannot be empty.]}
```
Does anyone know what is wrong?

**Comment by snaveen** [comment]
I saw your fix. It would be really helpful for me if this gets merged. Is there any workaround till that?

**Comment by joepurdy** [comment]
@snaveen My PR being merged is up to the maintainers of PagerDuty/go-pagerduty

If you want to use my fork for the time being I've gone and merged my fix into master there: https://github.com/joepurdy/go-pagerduty

I'll do my best to keep the fork updated with upstream, but ultimately the best fix would be the maintainers merging the fix into upstream.

**Comment by snaveen** [comment]
Thanks @joepurdy

**Comment by theckman** [comment]
I think I have merge access, let me see if I can do the needful tonight (Pacific time).

**Comment by snaveen** [comment]
> I think I have merge access, let me see if I can do the needful tonight (Pacific time).

@theckman could you help us on this?

**Comment by snaveen** [comment]
@theckman could you help us on this?

**Comment by snaveen** [comment]
@ranjib Could you help us on this?
