### ISSUE TITLE
Missing check for error in client.go

### ISSUE THREAD

**Issue by NautiluX** [PagerDuty/go-pagerduty#177]
#### Bug description

If this [function call](https://github.com/PagerDuty/go-pagerduty/blob/f60f4fc45222a1a50b1950dbb207508d1fc0da3a/client.go#L136) returns an error (I accidentally added a newline character to the end of the escalation policy id when called from [GetEscalationPolicy](https://github.com/PagerDuty/go-pagerduty/blob/f60f4fc45222a1a50b1950dbb207508d1fc0da3a/escalation_policy.go#L98)), the call in the [following line](https://github.com/PagerDuty/go-pagerduty/blob/f60f4fc45222a1a50b1950dbb207508d1fc0da3a/client.go#L137) may result in a crash as `req.Header` may be `nil`.

However, if `nil` would be returned in case of an error to [GetEscalationPolicy](https://github.com/PagerDuty/go-pagerduty/blob/f60f4fc45222a1a50b1950dbb207508d1fc0da3a/escalation_policy.go#L98), [this](https://github.com/PagerDuty/go-pagerduty/blob/f60f4fc45222a1a50b1950dbb207508d1fc0da3a/escalation_policy.go#L172) `defer` results in a crash as `res.Body` will be nil as well.

#### Expected behaviour

Erroneous input shouldn't result in a crash but the error being returned to the user.

**Comment by theckman** [comment]
This should have been fixed via #266.
