### ISSUE TITLE
service: SupportHours creation not supported

### ISSUE THREAD

**Issue by miekg** [PagerDuty/go-pagerduty#188]
Hello,

I'm trying to add SupportHours to an existing service or creating a service with SupportHours. Both things don't work but the failure mode is different:

* creating service w/ supporthours: `&{2001 Invalid Input Provided [params must be a Hash]}`, this is just filling out and using the SupportHours struct https://github.com/PagerDuty/go-pagerduty/blob/master/service.go#L42
* updating a service w/ supporthours: a 200 is returned, but nothing is updated on the service itself.

**Comment by n-apalm** [comment]
I am also seeing this issue with `SupportHours` . I see the same issues with related fields like `IncidentUrgency` . I am able to create a new service of any valid configuration, but I am then unable to update these fields. The same issue manifests where a 200 is erroneously returned. 

I am able to update the fields successfully when I test in Postman... Is there some discrepancy between the go client and the underlying API? I haven't been able to find any glaring payload differences.

I am wondering how the UI accomplishes these calls. Some form of editing `SupportHours` and `IncidentUrgencyRule` must be supported. Could the team shed some light on how to accomplish this?

**Comment by stmcallister** [comment]
Hello! So, I'm able to create SupportHours with the following:

```
service := pagerduty.Service{
	APIObject: pagerduty.APIObject{
		ID: "<myid>",
	},
	Name: "foo from go scratch 2",
	EscalationPolicy: pagerduty.EscalationPolicy{
		APIObject: pagerduty.APIObject{
			ID:   "<myid>",
			Type: "escalation_policy",
		},
	},
	SupportHours: &pagerduty.SupportHours{
		Type:       "fixed_time_per_day",
		Timezone:   "America/Lima",
		StartTime:  "09:00:00",
		EndTime:    "17:00:00",
		DaysOfWeek: []uint{1, 2, 3, 4, 5},
	},
	IncidentUrgencyRule: &pagerduty.IncidentUrgencyRule{
		Type: "use_support_hours",
		DuringSupportHours: &pagerduty.IncidentUrgencyType{
			Type:    "constant",
			Urgency: "high",
		},
		OutsideSupportHours: &pagerduty.IncidentUrgencyType{
			Type:    "constant",
			Urgency: "low",
		},
	},
	ScheduledActions: []pagerduty.ScheduledAction{
		{
			Type: "urgency_change",
			At: pagerduty.InlineModel{
				Type: "named_time",
				Name: "support_hours_start",
			},
			ToUrgency: "high",
		},
	},
}
```

However, i'm not able to update through the library OR Postman. @n-apalm am I reading correctly that you were able to update `support_hours` by calling the API directly through POSTMAN?

**Comment by n-apalm** [comment]
Yep, just tested again. Sending via Postman I get a `200`. The correct change is reflected in the response, as well as in the UI. Payload being:
```
{
    "service": {
        "id": <myid>,
        "status": "active",
        "alert_creation": "create_alerts_and_incidents",
        "escalation_policy": {
            "id": <myid>,
            "type": "escalation_policy_reference",
        },
      	"support_hours": {
          	"type": "fixed_time_per_day",
          	"time_zone": "America/Lima",
          	"start_time": "09:00:00",
			"end_time": "17:00:00",
          	"days_of_week": [1,2,3,4]
        },
      	"scheduled_actions": [
          {
            "type": "urgency_change",
            "at": {"type": "named_time", "name": "support_hours_start"},
            "to_urgency": "high"
          }
        ],
        "incident_urgency_rule": {
            "type": "use_support_hours",
          	"during_support_hours": {
            	"type": "constant",
              	"urgency": "high"
            },
          	"outside_support_hours": {
            	"type": "constant",
              	"urgency": "low"
            }
        },
        "acknowledgement_timeout": 120,
        "auto_resolve_timeout": 44,
        "type": "service",
    }
}
```

I am also able to successfully update with these different values (leaving the rest of the body unchanged):
```
      	"support_hours": {
          	"type": "fixed_time_per_day",
          	"time_zone": "America/Lima",
          	"start_time": "09:00:00",
			"end_time": "17:00:00",
          	"days_of_week": [1,2,3,4]
        },
      	"scheduled_actions": [],
        "incident_urgency_rule": {
            "type": "use_support_hours",
          	"during_support_hours": {
            	"type": "constant",
              	"urgency": "high"
            },
          	"outside_support_hours": {
            	"type": "constant",
              	"urgency": "severity_based"
            }
        },
```

and back down to no support hours or scheduled actions, incident urgency constant low:
```
        "incident_urgency_rule": {
            "type": "constant",
          	"urgency": "low"
        },
```

**Comment by n-apalm** [comment]
However, I am unable to mimic this behavior with the go client, even though I am using what appear to be the exact same values. I noticed the terraform project references a different go client repo that has slightly different Service structs. Are urgency / support hours updates working in that project? I haven't been able to try out that client yet since it would require a little bit of a refactor.

**Comment by n-apalm** [comment]
@stmcallister  I figured it out...

The JSON body on service UPDATE must be nested under a `service` key. It looks like the terraform client does this. Willing to bet this was the difference between our 2 Postman tests.
