### ISSUE TITLE
Allowing custom API endpoint in NewClient config

### ISSUE THREAD

**Issue by alibasim86** [PagerDuty/go-pagerduty#198]
Hi,

Can we allow API Endpoint customization during client creation to allow the run from an air gapped environment where calls are made via an API gateway.

https://github.com/PagerDuty/go-pagerduty/blob/44f00b57ce291cef4ae1e1cb3e0f8f3a0ceccbc6/client.go#L98

Thanks
Ali

**Comment by stmcallister** [comment]
Hi @alibasim86! That's an interesting thought. While we think about ways we could address this, does your API gateway support a proxy mode? We do pick up environment proxy settings if you have `HTTP_PROXY` or `HTTPS_PROXY`.

**Comment by alibasim86** [comment]
Hi, even if the API gateway supports its the system internally that is using the go-pagerduty will be pointing to a custom URL (that's the API gateway) to talk to PagerDuty public API endpoints for both API and events. 
ie:
api.pagerduty.com might be   vip.mydomain.com/api
events.pagerduty.com might be vip.mydomain.com/events 

Thanks
Ali

**Comment by stmcallister** [comment]
Would a function like this do the trick?

```go
func NewClientWithAPIEndpoint(authToken, apiEndpoint string) *Client {
	return &Client{
		authToken:   authToken,
		apiEndpoint: apiEndpoint,
		authType:    apiToken,
		HTTPClient:  defaultHTTPClient,
	}
}
```

**Comment by alibasim86** [comment]
yep, That would do it. Thank you

**Comment by stmcallister** [comment]
So, we went with a little bit different of an approach. The way you'll set a custom APIEndpoint will look something like this:

`client := NewClient("SOME_TOKEN", WithAPIEndpoint("https://mypdapi.com"))`

**Comment by stmcallister** [comment]
Please comment, or post another issue, if you have further trouble with this.
