### ISSUE TITLE
CreateEventWithHTTPClient panics if the request fails

### ISSUE THREAD

**Issue by cnmcavoy** [PagerDuty/go-pagerduty#211]
CreateEventWithHTTPClient panics on [L52](https://github.com/PagerDuty/go-pagerduty/blob/master/event.go#L52) because `resp` may be nil. Previous versions of the code did not attempt to inspect the `resp` struct and were unaffected. The bug seems to have been introduced in [this commit](https://github.com/PagerDuty/go-pagerduty/commit/cb8001f21274406fd3c62803cef4088e17477984#diff-9fb85d1ee9f1b0a59804bec41e1491fe).

**Comment by stmcallister** [comment]
Cleaning this up. Assuming #224 fixed this issue. Please open another issue if still having issues.
