### ISSUE TITLE
ManageIncidents - support set resolution

### ISSUE THREAD

**Issue by hagaishapira** [PagerDuty/go-pagerduty#243]
In case of incident resolution (status is resolved) the [API](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents/put) allows to set a resolution string.
As far as I can see, this is currently not supported.

**Comment by theckman** [comment]
@hagaishapira would you be willing / able to get a PR raised to add that field to this type: https://github.com/PagerDuty/go-pagerduty/blob/69ade4b95ef0ff1d582a7d9f226a98f9db886df1/incident.go#L155-L162

The reason I ask is that I have permission to review and merge the PRs of others, and not my own, so an external contribution is easier for me to shepherd towards release.

**Comment by theckman** [comment]
@hagaishapira I went ahead and raised a PR since I didn't hear back from you. Your request should make it as part of v1.4.0 when it's eventually released.
