### ISSUE TITLE
`opts.Since` doesn't work properly

### ISSUE THREAD

**Issue by atmosx** [PagerDuty/go-pagerduty#244]
Hello,

The application I'm writing fetches incidents occurred the last 1 minute(s). I'm using `opts.Since` to fetch the results, but the API is not returning the expected results. Here's an example:

```go
func FetchRecent(limit int, token string, sinceDate string) map[string]float64 {
	// setup options
	var opts pagerduty.ListIncidentsOptions
	opts.Offset = uint(1)
	opts.Limit = 100
	opts.TimeZone = "UTC"
	opts.Since = sinceDate
	// setup variables
         [...]
	// parse duration
	for {
		list, err := client.ListIncidents(opts)
		if err != nil {
			[...]
		}
		for _, i := range list.Incidents {
			logger.Info("Found incident", "title", i.Title, "description", i.Description, "status", i.Status, "created", i.CreatedAt)
			[...]
		}
		if !list.More {
			// logger.Debug("no more incidents found!")
			break
		}
		opts.Offset++
	}
	return alerts
}
```

Now if `opts.Since` is set to `2020-10-06T10:30:00` I can see the incident created at `2020-10-06T11:08:29Z` according to the API. If I use a time closer to the incident, such as `2020-10-06T10:31:00` as `opts.Since`, I get no results back.

Any ideas? 🤔

**Comment by theckman** [comment]
What if you set the Until time?

**Comment by atmosx** [comment]
> What if you set the Until time?

I use until doesn't work at all:

```
opts.Since = "2020-10-06T10:30:00"
opts.Until = "2020-10-06T11:30:00"
```

doesn't display the `2020-10-06T11:08:29Z` incident. As a workaround setting `opts.Since` to `time.now().Add(d)` where `d` is `time.ParseDuration("-2h")`. Then I'm fetching all incidents every minute and compare `createdAt` and `LastStatusChangeAt` which are date strings in `RFC3339` format  and check if any these dates falls within the a 2 minutes threshold.

Works, but is unnecessarily complicated.

**Comment by theckman** [comment]
I'll see if I can try to allocate some time to confirm whether or not this seems to be an issue on our side, or an issue with their API. Since changing the time makes it work, my suspicion is that it's not an issue with us and it's something with them.

**Comment by theckman** [comment]
@atmosx do you know if you're still seeing this happen?

**Comment by atmosx** [comment]
> @atmosx do you know if you're still seeing this happen?

Switched jobs, we're using betterUptime now, so as far as I'm concerned you can close this.

Ty!

**Comment by theckman** [comment]
:+1:
