### ISSUE TITLE
Support for (assigning and querying on) Tags

### ISSUE THREAD

**Issue by metskem** [PagerDuty/go-pagerduty#249]
I see the [PagerDuty REST api supports Tags](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1tags/get), but I don't see any support for Tags in this golang library.

Am I correct?
And if so, are there any plans to support it?

**Comment by stmcallister** [comment]
You are  correct! Adding support for tags in the library is definitely on my radar. Will hopefully be able to get to it soon.

**Comment by stmcallister** [comment]
closing this as support for tags has been merged to master.
