### ISSUE TITLE
ID generator for APIObject struct does not exist

### ISSUE THREAD

**Issue by gerardocorea** [PagerDuty/go-pagerduty#314]
Starting to look into using this library but I am noticing that some sort of function to generate a none existing ID for that resource type does not exist. Are we expected to always generate one ourselves?

**Comment by theckman** [comment]
For the create you're supposed to leave it empty, PagerDuty generates it server side and provides it back in the response. We do the same in our client.

**Comment by theckman** [comment]
@gerardocorea I'll close this issue now; let us know if you have any other follow-up questions.

**Comment by gerardocorea** [comment]
Thank you for the insight, you are correct @theckman. A quick follow up question. If I wanted to update an existing integration for a service, is the only way to achieve this is to get a list of all the services(iterate over the the list to find the one I want and grab its ID) then grab the list of integrations for that service(iterate over the list of integrations and grab the specific ID) and then perform and update against that integration?

**Comment by theckman** [comment]
@gerardocorea assuming you don't know the IDs beforehand, yeah that's what you have to do.
