### ISSUE TITLE
Add ability to create or update integrations with email filter rules

### ISSUE THREAD

**Issue by gerardocorea** [PagerDuty/go-pagerduty#315]
The pagerduty api supports fields for email integrations that allows specification from regex's and how to handle creation of incidents. Adding in structs for these properties can make it easier to manage these rules.

https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1services~1%7Bid%7D~1integrations~1%7Bintegration_id%7D/put

Example API call that can be used below.
```
{
  "integration": {
    "id": "ID",
    "type": "generic_email_inbound_integration",
    "summary": "Email",
    "self": "https://api.pagerduty.com/services/ID/integrations/ID",
    "html_url": "https://test.pagerduty.com/services/ID/integrations/ID",
    "name": "Email",
    "service": {
      "id": "ID",
      "type": "service_reference",
      "summary": "import-csv",
      "self": "https://api.pagerduty.com/services/ID",
      "html_url": "https://ukg-dev.pagerduty.com/service-directory/ID"
    },
    "created_at": "2021-03-18T13:52:41-04:00",
    "vendor": {
      "id": "PBPQJ1M",
      "type": "vendor_reference",
      "summary": "Email",
      "self": "https://api.pagerduty.com/vendors/ID",
      "html_url": null
    },
    "integration_email": "import-csv@test.com",
    "email_incident_creation": "on_new_email_subject",
    "email_filter_mode": "or-rules-email",
    "email_filters": [
      {
        "subject_mode": "always",
        "subject_regex": null,
        "body_mode": "match",
        "body_regex": "test",
        "from_email_mode": "always",
        "from_email_regex": null,
        "id": "ID"
      },
    ],
    "email_parsers": null,
    "email_parsing_fallback": null
  }
}
```

**Comment by theckman** [comment]
@gerardocorea I'm an outside contributor to this repo, but PagerDuty has set a policy of not supporting undocumented API features in the client. As best I can tell the field you refer to isn't documented on that URL, and so we cannot support this functionality until they add documentation for it.

@stmcallister would you be able to also relay the request that this be documented?

**Comment by gerardocorea** [comment]
Sounds good, I have a working version of this which im sure could use some feedback. If there also a way in which I can contribute back the documentation please feel free to let me know.

**Comment by theckman** [comment]
@gerardocorea sorry that I missed your question before now. As I recall, that's something that internal product folks at PagerDuty need to do. I had asked the same question once. 😉

**Comment by theckman** [comment]
Good news, this is documented now! I'll make this part of the WIP v1.5.0 release.

https://developer.pagerduty.com/api-reference/b3A6Mjc0ODIwMw-create-a-new-integration
https://developer.pagerduty.com/api-reference/b3A6Mjc0ODIwNA-update-an-existing-integration

**Comment by theckman** [comment]
I raised #385 to address this feature request.
