### ISSUE TITLE
Feature Request: Add field "Bio" from Pagerduty to reports

### ISSUE THREAD

**Issue by mike-migale-cko** [PagerDuty/go-pagerduty#344]
Hi everyone, would it be possible to add the field "Bio" to the report?
In our use case, each person has a unique ID used for different purposes but we can identify users with the ID (not Pagerduty User ID). We would include the ID in the BIO section of Pagerduty.
It would be nice if we can produce reports taking the "Bio" from Pagerduty API and adding it to the report. Is this something possible to achieve?
e.g. Bio in pagerduty = 3456
Report prints bio - name - hours, etc ( 3456 - Username Usersurname | xyz hours ...)
Thanks in advance.

**Comment by theckman** [comment]
@mike-migale-cko I am not quite sure what you mean when you say the report. Could you clarify.

Per the [API docs](https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1users/post), the Description field of the user is their bio. The User struct has that field: https://pkg.go.dev/github.com/PagerDuty/go-pagerduty@master#User.

Does that solve your need?

**Comment by mike-migale-cko** [comment]
Hi Tim, apologies, yes it can be the "Description" field. For report, I mean when producing the on-call report (in any format). Let me know if this clarifies the question. Thanks in advance.

**Comment by theckman** [comment]
@mike-migale-cko it doesn't, unfortunately. How are you generating one of these reports in Go with this client? I don't see any methods specific to that, so it's not clear to me where we would add that functionality in this repository or whether that's even something the PagerDuty API supports.

**Comment by theckman** [comment]
@mike-migale-cko I'm still not sure that I understand this feature request, and wonder if you could help me understand which API you're talking about implementing in the client.

**Comment by theckman** [comment]
@mike-migale-cko I'm still not sure what feature this is requesting specifically, so I'm going to close this issue. If you'd like to re-raise the feature request, please don't hesitate to open a new issue. When opening that issue, please provide details about which PagerDuty REST API you're looking to have this client expand its support of.

Please note, this repo is largely maintained by someone who is not a PagerDuty employee. So if you're looking to make a _product_ feature request, and not requesting this library support a feature already offered, you'd want to reach out to PagerDuty support.
