### ISSUE TITLE
Backward incompatability - CreateService - existing setup works in 1.3.0 but not in 1.4.x

### ISSUE THREAD

**Issue by onikroo** [PagerDuty/go-pagerduty#346]
Have an existing module used to create a service with 1.3.0, which now fails following update to 1.4.x

Steps to reproduce:

1. Create API client using API token:
`client := pagerduty.NewClient(*currentModel.PagerDutyToken)`

2. Get escalation policy:
`escalationpolicy, err := client.GetEscalationPolicy(*currentModel.EscalationPolicyID, &pagerduty.GetEscalationPolicyOptions{})`

3. Populate service params:
`service := pagerduty.Service{
		Name:             *currentModel.Name,
		Description:      *currentModel.Description,
		EscalationPolicy: *EscalationPolicy,
}`

4. Create service:
`res, err := client.CreateService(service)`

The error caught in 1.4.x is:
`HTTP response failed with status code 400, message: Invalid Input Provided (code: 2001)`

In 1.3.0 this creates successfully.

Have tested this with the same code and variables across both versions, and can confirm rolling back to 1.3.0 works as expected once again.

**Comment by theckman** [comment]
Apologies for this. I'll work on tracking this down over the next day or so.

**Comment by theckman** [comment]
It looks like it's because of the new fields that got added to the `Service` type, `SupportHours` and `ScheduledActions`. I think adding `omitempty` to both should fix this.

**Comment by theckman** [comment]
I'm prepping the `v1.4.2` release now, and it should be available within the hour so I'll close this issue.

**Comment by theckman** [comment]
It's now available.
