### ISSUE TITLE
List Incidents Method -Options not working as expected.

### ISSUE THREAD

**Issue by MadhavanPillai** [PagerDuty/go-pagerduty#362]
https://github.com/PagerDuty/go-pagerduty/blob/340f6d5a093d6445012eb08ab560ad828f51e561/incident.go#L131

The new list_incidents method when used with options like 'status' does not filter correctly.

Observed Response: When I use filters: {'incident_key': 'test', 'status':'triggered'} . in the response I get incidents with 'status': resolved as well.
Expected Response:
Only incidents with status: 'triggered' should be listed.

**Comment by theckman** [comment]
@MadhavanPillai could you provide an example snippet you are able to reproduce this with? Also, which version of Go and which version of `go-pagerduty` are you using?

**Comment by theckman** [comment]
I tried to reproduce this myself with my developer PagerDuty account, and I wasn't able to. This snippet worked as expected on Go 1.16.6 with the latest commit on the `master` branch:

```Go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/PagerDuty/go-pagerduty"
)

func main() {
	k := os.Getenv("PD_API_KEY")
	if len(k) == 0 {
		log.Fatal("PD_API_KEY must be set")
	}

	c := pagerduty.NewClient(k)

	opts := pagerduty.ListIncidentsOptions{
		IncidentKey: "foobar",
		Statuses: []string{
			"resolved",
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)

	defer cancel()

	incs, err := c.ListIncidentsWithContext(ctx, opts)
	if err != nil {
		log.Fatalf("failed to list incidents: %v", err)
	}

	fmt.Printf("%+v\n", incs)
}

```

**Comment by theckman** [comment]
@MadhavanPillai have you been able to take a look at my questions above or been able to run the snippet I shared? With me not being able to reproduce your issue, I'm not sure how to debug this further without more details from you.

**Comment by theckman** [comment]
@MadhavanPillai wanted to ping one last time to see if you'd be able to let me know if you could help me try to reproduce it. Otherwise I probably will need to close this issue, pending any further reports.

**Comment by theckman** [comment]
@MadhavanPillai I'm going to close the issue at this time, but please feel free to open a new issue if you are continuing to experience this or if you run into any other problems.
