### ISSUE TITLE
ManageIncidentsOptions doesn't take EscalationLevel

### ISSUE THREAD

**Issue by sim1s** [PagerDuty/go-pagerduty#364]
While trying to use the go-pagerduty client to escalate an incident, I noticed that EscalationLevel is missing in ManageIncidentsOptions

https://github.com/PagerDuty/go-pagerduty/blob/340f6d5a093d6445012eb08ab560ad828f51e561/incident.go#L169-L177

The payload for the API allows for escalation_level

https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1incidents/put

**Comment by theckman** [comment]
@sim1s do you know whether that field uses zero-based indices? They don't show an example, so I'm not sure if the second escalation level is `1` or `2`. Also, might you have the spare cycles to raise a PR to add this? 

For some context, this library is largely community maintained, and while I can review and merge PRs contributed by others I cannot merge my own and must wait for a PD employee to have some time to review my changes.

If you had the time to raise the PR and address any feedback, it would make it so I could merge it in to eventually be released with v1.5.0.

**Comment by sim1s** [comment]
@theckman the field does not use zero-based indices, the first escalation level is `1`.  The response also does not specify which escalation level is currently triggered, and sending a value of `0` or `1` brings the escalation down to the lowest level (first responders).  

[Here's a PR to resolve this](https://github.com/PagerDuty/go-pagerduty/pull/366)
