### ISSUE TITLE
Setting conference information in new incident

### ISSUE THREAD

**Issue by bparlidoordash** [PagerDuty/go-pagerduty#373]
Hello, I'm looking to set the conference url and number when creating a new incident, however, I don't see a way to do that with this package? The [API supports](https://developer.pagerduty.com/api-reference/b3A6Mjc0ODE0MA-create-an-incident) it, but not the `CreateIncidentOptions` type.  And AFAICT the `Incident` type (which does have `ConferenceBridge`) is only used in responses from the API.

Am I overlooking something or would this be a feature request?

**Comment by theckman** [comment]
This would be a feature request. 😄 

If you had some time to add it to this `CreateIncidentOptions` struct, update the tests as needed, and open a PR, I'd greatly appreciate it. It's much for me to merge PRs of others merged than my own. 👍 

https://github.com/PagerDuty/go-pagerduty/blob/ad98290ed37bd905d8330a4e3c98d55b302d3f08/incident.go#L153-L164

**Comment by bparlidoordash** [comment]
Thank you @theckman! Looks like you already go to it
