### ISSUE TITLE
Add Event Orchestrations API

### ISSUE THREAD

**Issue by trevorriles** [PagerDuty/go-pagerduty#424]
It looks like the Event Orchestration framework is becoming an alternative to RuleSets. Can this be supported by the go api?

**Comment by theckman** [comment]
We tend to only support what's available in the public documentation, so as long as PD havs documented everything on their side there should be nothing stopping us from including it (beyond someone implementing the code).

@trevorriles to that point, would you be willing to help implement this by raising a PR and work through resolving any feedback?

**Comment by theckman** [comment]
@trevorriles wanted to reach back out to see if you wanted to contribute this.

**Comment by trevorriles** [comment]
Hey sorry, for my purposes the older rule sets work for me. Was mostly looking to see if the new features were available to use instead.

That being said if I come by some free time I may take a stab at it in the future if nobody else gets to it.
