### ISSUE TITLE
Get Service With Context returns error "HTTP response with status code 401 does not contain Content-Type: application/json"

### ISSUE THREAD

**Issue by mehulgohil** [PagerDuty/go-pagerduty#469]
GetServiceWithContext expects a Header Content-Type: application/json
Currently in the go-pagerduty sdk we are not passing the header.

As per Pagerduty Api Docs - https://developer.pagerduty.com/api-reference/165ad96a22ffd-get-a-service
Get Service API needs this header as required

![image](https://user-images.githubusercontent.com/28588619/203791789-5ff733d6-0b10-4a84-b1d2-a41bbc3c5e6b.png)

**Comment by theckman** [comment]
@mehulgohil that's not what this error means. The error is saying that the PagerDuty API returned an HTTP 401 in response to your request, and the response body was not JSON. The PagerDuty Go client does not attempt to parse the response if it's not JSON.

HTTP 401 is the Unauthorized status code, which indicates you provided invalid credentials when calling the PagerDuty API.

**Comment by mehulgohil** [comment]
Sorry, my bad was the token issue. Thanks

**Comment by nanmu42** [comment]
I just ran into this problem and found the error message `HTTP response with status code 401 does not contain Content-Type: application/json` is a little confusing.

`HTTP response with status code 401` may be just fine.
