### ISSUE TITLE
breaking change in a minor update

### ISSUE THREAD

**Issue by goddenrich** [PagerDuty/go-pagerduty#470]
We recently upgraded from v1.3.0 to v1.6.0 and there was a breaking api change https://github.com/PagerDuty/go-pagerduty/commit/271420668dee5b1e403cbf52924f2dce3c24ad4f what are your controls in place to ensure you don't make breaking changes without bumping the major version?

**Comment by ChuckCrawford** [comment]
@goddenrich: We apologize for the inconvenience but we are doing our best to balance improving the library for everyone with avoiding breaking changes.

The release notes for the [1.5.0 release](https://github.com/PagerDuty/go-pagerduty/releases/tag/v1.5.0) and the [1.6.0 release](https://github.com/PagerDuty/go-pagerduty/releases/tag/v1.6.0) call out these changes and describe our rationale for making them.
