### ISSUE TITLE
Missing support for raw analytics

### ISSUE THREAD

**Issue by ztzxt** [PagerDuty/go-pagerduty#471]
Hi, as fas as I could see Go client doesn't support those two endpoints:

> https://developer.pagerduty.com/api-reference/c2d493e995071-get-raw-data-multiple-incidents

> https://developer.pagerduty.com/api-reference/328d94baeaa0e-get-raw-data-single-incident

Are those endpoints supported in client library? I would love to try implementing them if they don't exist yet.

**Comment by ChuckCrawford** [comment]
I would guess they are not yet implemented since they are in Early Access. I am not 100% sure how we have handled Early Access APIs in our client library but I would welcome the PR if you wanted to attempt adding the support...

**Comment by ChuckCrawford** [comment]
This should now be resolved with: https://github.com/PagerDuty/go-pagerduty/pull/481
