### ISSUE TITLE
Please add support for the license APIs

### ISSUE THREAD

**Issue by mk23** [PagerDuty/go-pagerduty#480]
* https://developer.pagerduty.com/api-reference/10230a10c519e-list-license-allocations
* https://developer.pagerduty.com/api-reference/4c10cb38f7381-list-licenses

**Comment by gerardocorea** [comment]
Wouldn't mind take a stab at this. Is there any specific process to confirm this would be approved if the implementation is accepted?

**Comment by ChuckCrawford** [comment]
@gerardocorea : if you put up a PR we will do our best to get it reviewed and merged. You can `@me` when you get it done...

**Comment by gerardocorea** [comment]
@ChuckCrawford Thanks for the response, what might be the best way to go about testing this if someone doesn't have access to an enterprise account with licenses.

**Comment by gerardocorea** [comment]
@ChuckCrawford opened a PR for this request.
