### ISSUE TITLE
Cannot grok how to construct a ResponderRequestOptions!

### ISSUE THREAD

**Issue by andrewwatson** [PagerDuty/go-pagerduty#485]
Does anyone have an example of how to add an escalation policy to an incident as a responder? The example on the api docs site doesn't use the SDK, it uses http to POST a JSON blob to the API!

I've tried a lot of different things but I keep running into type issues.

Thanks

**Comment by andrewwatson** [comment]
Also, also... I kinda found my answer in a unit test! 

```go
	request_target := ResponderRequestTarget{}
	request_target.ID = "PJ25ZYX"
	request_target.Type = "user_reference"

	request_target_wrapper := ResponderRequestTargetWrapper{Target: request_target}
	request_targets := []ResponderRequestTargetWrapper{request_target_wrapper}

	input := ResponderRequestOptions{
		From:        from,
		Message:     "Help",
		RequesterID: "PL1JMK5",
		Targets:     request_targets,
	}
```

So I think will write this up as an example and submit a PR...

**Comment by ChuckCrawford** [comment]
Glad you got this figured out @andrewwatson . Can we close this issue?

**Comment by andrewwatson** [comment]
Yeah that's fine. Thanks!
