### ISSUE TITLE
ResolvedAt field missing from Incident struct

### ISSUE THREAD

**Issue by dnwe** [PagerDuty/go-pagerduty#486]
I wanted to use the `resolved_at` field from the go-pagerduty API to allow me to show the duration of resolved incidents in the same way as the PagerDuty UI does. However, I noticed it was missing from the Incident struct. In the short term I used `LastStatusChangeAt` (`last_status_change_at`), but it would be good to have the proper field available and populated

I see that a PR already exists at https://github.com/PagerDuty/go-pagerduty/pull/482 and worked well in my testing

**Comment by ChuckCrawford** [comment]
This will be included in the 1.8.0 release.
