### ISSUE TITLE
Create releases with built binaries

### ISSUE THREAD

**Issue by cmluciano** [PagerDuty/go-pagerduty#50]
I would love to create binary releases for each new pd release if possible. I'm to port over the methods that we use in [packer-builder-softlayer](https://github.com/watson-platform/packer-builder-softlayer/releases). 

The only pre-requisite is having a [secure API key](https://github.com/watson-platform/packer-builder-softlayer/blob/master/.travis.yml#L21-L22) for travis to build these. Is this something that others would be interested in?

**Comment by ranjib** [comment]
@cmluciano as of now, I am working on full api coverage. Once thats done and the CLI is bit more tested I'll publish a binary. I cant promise this to be happening this year at least

**Comment by stmcallister** [comment]
Does this issue still need to be addressed? Happy to help, if so. 

Going to close this issue. But, please comment here, or create a new issue and let us know how we can help. Thanks!
