### ISSUE TITLE
service: auto_resolve_timeout & acknowledgement_timeout cannot be set to null

### ISSUE THREAD

**Issue by heimweh** [PagerDuty/go-pagerduty#51]
Hi,

It seems like the API allows the JSON value **null** (tested it via https://v2.developer.pagerduty.com/v2/page/api-reference#!/Services/put_services_id) to be passed which would disable the `auto_resolve_timeout` (as well as `acknowledgement_timeout` and possibly others) but it doesn't seem like the client library support it yet.

Here's a screenshot:
![screen shot 2016-11-04 at 13 26 45](https://cloud.githubusercontent.com/assets/13624191/20006694/12b198e8-a299-11e6-9944-ff76d4e5ef30.png)

I'd be happy to help out on this one but not quite sure where to start.

**Comment by ranjib** [comment]
@heimweh current implementation uses an uint pointer https://github.com/PagerDuty/go-pagerduty/blob/master/service.go#L62 for the service struct. If you remove "omitempty" from the annotation of AutoResolveTimeout field, I think that will solve your use case.

**Comment by heimweh** [comment]
@ranjib: thanks for looking into this. I'll take a look and see if I can get this to work. I think we need to cover three use cases though. 

1. Use API defaults by just omitting the fields
2. Disable the timeouts by passing empty("null") fields
3. User-defined timeouts

Is this something we want or do we want to just handle user-defined timeouts or have them disabled?
