### ISSUE TITLE
Escalation Policy's repeat_enabled Is Ignored

### ISSUE THREAD

**Issue by dthagard** [PagerDuty/go-pagerduty#57]
It doesn't matter if I explicitly set the repeat_enabled flag when making a call to the PagerDuty API for an escalation policy--either way the value is ignored. Also, I don't get a value back for this option when calling the API.

**Comment by Deconstrained** [comment]
In my tests, I have determined that this is not particular to `go-pagerduty` but rather applies to the API itself. Hence, I have documented and reported it to the PagerDuty engineering team.
