### ISSUE TITLE
Memory leak because of response body is not closed

### ISSUE THREAD

**Issue by AngelRefael** [PagerDuty/go-pagerduty#66]
There is a memory leak in event.go - func CreateEvent, the closing of the response must take place right after the checking of the error, currently when the response status is not equal to 200, the response body will not be closed - see pull request [#65](https://github.com/PagerDuty/go-pagerduty/pull/65)

**Comment by lfepp** [comment]
Fixed with [PR#65](https://github.com/PagerDuty/go-pagerduty/pull/65)
