### ISSUE TITLE
Package test coverage is lacking

### ISSUE THREAD

**Issue by theckman** [PagerDuty/go-pagerduty#70]
PagerDuty is a service that we've come to expect to be reliable and trustworthy. It's one of the few services in the world expected to be fully operational if things go sideways with major hosting providers. However, you can only be this way if you test the system to ensure its proper operation. It's why Failure Friday became a core tenet of Engineering at PagerDuty.

I'd like to use this client, and to trust its operation, that doesn't seem possible with the current lack of test coverage. Would it be possible to prioritize some testing of this package to catch bugs?

**Comment by stmcallister** [comment]
All true! Hopefully #190 was a good start for this. Please open another issue or comment here if that is not the case.
