### ISSUE TITLE
Publish CLI binaries as releases

### ISSUE THREAD

**Issue by ethanfrogers** [PagerDuty/go-pagerduty#81]
Would it be possible to start publishing releases of the CLI to Github releases? `go install github.com/PagerDuty/go-pagerduty` doesn't install the binary to the `$GOPATH/bin` and they only way I see to get access to the CLI is to compile it and link it yourself. This would make it really useful for folks using it in CI/CD scripts, for instance.

**Comment by stmcallister** [comment]
Assuming that #123 resolved this issue. Please comment or open a new issue if this needs to be discussed further.  Thanks!
