### ISSUE TITLE
Support V2 events

### ISSUE THREAD

**Issue by tmccleve** [PagerDuty/go-pagerduty#83]
In order to leverage the new severity feature for PagerDuty events, this must be updated to utilize the v2 of the events api. I'm willing to do most of the work on updating. I'm looking for some guidance on how the maintainers would prefer to approach backward compatibility with the V1 events.

**Comment by tmccleve** [comment]
Spiked this out for anyone that's interested. https://github.com/TWExchangeSolutions/prtg-pagerduty/tree/master/event

**Comment by stmcallister** [comment]
Cleaning out old issues. This one appears to be addressed. Please repost if not.
