### ISSUE TITLE
Help with incident creation API

### ISSUE THREAD

**Issue by mmcloughlin** [PagerDuty/go-pagerduty#89]
This is not specifically an issue with the `go-pagerduty` package but I was hoping somebody here might be able to help. I'm having trouble getting the incident creation `POST` endpoint to work.

I've copy pasted the request body found on https://v2.developer.pagerduty.com/docs/incident-creation-api

```json
{
  "incident": {
    "title": "Your desk is on fire!",
    "service": {
      "id": "PW7YESS",
      "type": "service_reference"
    },
    "assignments": [{
      "assignee" : {
    	  "id": "PZUVZZZ",
    	  "type": "user_reference"
      }
    }]
  }
}
```

I substituted IDs from my team's pagerduty. The response I got back was HTTP 400 with an unhelpful error message

```json
{"error":{"message":"Invalid Input Provided","code":2001,"errors":["params must be a Hash"]}}
```

Any guidance?

**Comment by mmcloughlin** [comment]
My bad... missing a `Content-Type` header.

**Comment by mdeggies** [comment]
Thanks for posting the solution- it's not obvious from the error msg.

**Comment by izinda** [comment]
This error message is incredibly misleading. I would consider this a bug.

**Comment by Cescante** [comment]
Looks like this is a catch-all generic error. When my request body is malformed e.g. accidentally put the incident in a list, the exact same error was returned.
