### ISSUE TITLE
Assignment struct has no json conversion

### ISSUE THREAD

**Issue by bradleyrobinson** [PagerDuty/go-pagerduty#92]
This causes problems for some of the methods. For example, I spent a long time trying to figure out why the ManageIncidents method kept giving this message:

```Unable to acknowledge Failed call API endpoint. HTTP response code: 400. Error: &{2001 Invalid Input Provided [Assignee cannot be empty.]}```

I can make that change and make a pull request if needed, though it was a simple fix once I figured out what was wrong

**Comment by vanugrah** [comment]
@bradleyrobinson - Would you mind sharing what the fix was? I'm trying to create an array of UserReferences and I'm getting the same error: 

```
 "assignments": [{
    		"id": "ABCDEFG",
    		"type": "user_reference"
    	}]
```

**Comment by bradleyrobinson** [comment]
The code is missing json tags, my pull request fixes the error: https://github.com/PagerDuty/go-pagerduty/pull/93/commits/8207ed91570a30f3a976a4814f9eaa55ccc6ee41

**Comment by wdhnl** [comment]
Can someone from PD take a look at this?

**Comment by stmcallister** [comment]
Thanks for the PR @bradleyrobinson ! Appears #93 solved this. Closing.
